// <auto-generated />
using System;
using EsolApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EsolApp.Data.Migrations
{
    [DbContext(typeof(EsolAppDbContext))]
    [Migration("20191030061247_update-1312-39102019")]
    partial class update131239102019
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EsolApp.Data.Model.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Base64Image");

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("TodoId");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("EsolApp.Data.Model.TodoShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<int?>("TodosId");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("TodosId");

                    b.ToTable("TodoShare");
                });

            modelBuilder.Entity("EsolApp.Data.Model.Todos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateBy");

                    b.Property<DateTime?>("CreateDate");

                    b.Property<string>("Description");

                    b.Property<string>("ModifyBy");

                    b.Property<DateTime?>("ModifyDate");

                    b.Property<bool>("Status");

                    b.Property<string>("TodoName");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("EsolApp.Data.Model.Images", b =>
                {
                    b.HasOne("EsolApp.Data.Model.Todos", "Todo")
                        .WithMany("Images")
                        .HasForeignKey("TodoId");
                });

            modelBuilder.Entity("EsolApp.Data.Model.TodoShare", b =>
                {
                    b.HasOne("EsolApp.Data.Model.Todos", "Todos")
                        .WithMany("TodoShares")
                        .HasForeignKey("TodosId");
                });
#pragma warning restore 612, 618
        }
    }
}
